# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: ift ${{ matrix.swift }} on ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.7"]
    runs-on: ${{ ubuntu-latest }}
    
    
    steps:
      - uses: actions/checkout@v3
      
      - working-directory: ./myapp  
        run: npm ci
        
      - working-directory: ./myapp
        run: npm run build --if-present
      
      - working-directory: ./myapp
        run: npm install
        
      - working-directory: ./myapp
        run: npm test
        
      - working-directory: ./myapp
        run: node index.js &
        
      - working-directory: ./myapp
        run: curl "http://localhost:3000/data/2.5/weather"
      
  
  
      
      - name: Build
        working-directory: ./MyLibrary
        run: swift build
        
      - name: Run tests
        working-directory: ./MyLibrary
        run: swift test --enable-code-coverage
        
