# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: ift ${{ matrix.swift }} on ${{ matrix.os }}
    
    runs-on: ${{ ubuntu-latest }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.3"]

    steps:
      - uses: actions/checkout@v3
      - working-directory: ./myapp

        
      - run: npm ci
      - run: npm run build --if-present
      - run: npm install
      - run: npm test
      - run: node index.js &
      - run: curl "http://localhost:3000/data/2.5/weather"
      
  
  
      - working-directory: ./cs561-swift/MyLibrary
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test --enable-code-coverage
        
